# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 86400 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  events: #触发器
    - timer: #进店领豆#签到脚本#店铺签到#柠檬赚金币#愤怒的锦鲤#京东极速版红包#柠檬推一推#十元街#小鸽有礼#店铺签到#摇京豆
        parameters:
          name: 1jd_bean_sign
          cronExpression: "30 0 0,12,14 * * * *"
          enable: true
          argument: jd_shop&JD_DailyBonus&jd_shop_sign&jd_dpqd&jd_zjb&jd_angryKoi&jd_speed_redpocke&jd_tyt&jd_tuijinbi&jd_syj&jd_daily_lottery&jd_nzmh&jd_shop_sign1&jd_club_lottery&
    - timer: #京喜财富岛提现#京东汽车#汽车兑换金豆#京喜工厂开团#京东保价#工厂抢茅台#京喜工厂开团#汪汪乐园开工位#宠汪汪积分兑换奖品
        parameters:
          name: 2cfdtx_xtg
          cronExpression: "0 0 0,12,14-22/2 * * * *"
          enable: true
          argument: jd_cfdtx&jd_car&jd_car_exchange&jd_dreamFactory_tuan&jd_jxgc&jd_price&jd_dreamFactory_tuan&jd_dogsEmploy&jd_joy_reward
    - timer: #京东月资产变动通知#京豆变动通知#取关主播#京喜牧场#东东萌宠#小米-星空大冒险#京东试用
        parameters:
          name: 3jd_try
          cronExpression: "0 30 0,7 * * * *"
          enable: true
          argument: jd_all_bean_change&jd_bean_change&jd_unsubscriLive&jd_jxmc&jd_pet&gua_xmGame&jd_try
    - timer: #玩一玩成就#翻翻乐#东东乐园#东东电竞经理#摇钱树#京东全民开红包#东东超市#天天提鹅#金融养猪#京喜工厂#东东小窝#东东工厂#京东快递签到#京东直播#京东赚赚#狂欢欧洲杯#金榜创造营#京东零食街#全民挖现金#全民抢京豆#明星小店#特物Z|万物#特务Z行动-星小店#特物Z密室大逃脱#旺财乐园#京东全民开红包#滴滴橙心果园脚本#京喜财富岛#种豆得豆
        parameters:
          name: 4jd_joy-park
          cronExpression: "2 15,45 7,8-23/2 * * * *"
          enable: true
          argument: jd_wyw&jd_big_winner&jd_fcffl&jd_ddnc_farmpark&jd_Elecsport&jd_esManager&jd_djjl&jd_moneyTree&jd_redPacket&jd_superMarket&jd_daily_egg&jd_pigPet&jd_dreamFactory&jd_small_home&jd_jdfactory&jd_kd&jd_live&jd_jdzz&jd_europeancup&jd_gold_creator&jd_wxj&jd_qjd&jd_star_shop&jd_superBrand&jd_twz-star&jd_twmsdtt&jd_joy-park&jd_redPacket&dd_bucketWater&jx_cfd&jd_plantBean
    - timer: #京喜签到新签到#宠汪汪偷狗粮
        parameters:
          name: 5joy_park
          cronExpression: "40,1 0-23/1 * * *"
          enable: true
          argument: jd_jxqd_new&jd_joy_park&jd_joy_steal&
    - timer: #极速版签到+赚现金#京东秒秒币#真·抢京豆#升级赚京豆#签到脚本#愤怒的现金#天天优惠大乐透#赚30元 #领金贴#新潮品牌狂欢#京喜领88元红包#京喜签到#京喜签到新签到#幸运大转盘#闪购盲盒#来客有礼小程序#柠檬邀请有礼#抢京豆#宠汪汪赛跑助力#京东到家鲜豆任务#京东到家果园 #京东到家果园水车#京东到家鲜豆庄园收水滴#京东到家鲜豆庄园#京东签到图形验证#开学充电站
        parameters:
          name: 6jd_ms
          cronExpression: "0 10,20,30,40,50 0-23/1 * * * *"
          enable: true
          argument: jd_speed_sign&jd_ms&jd_angryBean&gua_MMdou&jd_goodMorning&jd_dpqd&jd_earn30&jd_jin_tie&jd_mcxhd&jd_jxlhb&jd_jxqd&jx_sign&jd_market_lottery&jd_sgmh&jd_sendBeans&jd_yqyl&jd_bean_home&jd_joy_run&jd_dj_bean&jd_dj_fruit&jd_dj_fruit_collectWater&jd_dj_getPoints&jd_dj_plantBeans&jd_sign_graphics&zy_kxcdz
    - timer: #清空购物车#东东农场#宠汪汪#签到领现金#点点券#手机狂欢城#手机狂欢城活动#热血心跳,狂解压#发财大赢家助力#粉丝互动#金机奖投票#5G超级盲盒#美丽研究院
        parameters:
          name: 7jd_mohe
          cronExpression: "1,1 0-23/1 * * *"
          enable: true
          argument: jd_cleancart&jd_fruit&jd_joy&jd_cash&jd_joy_feedPets&jd_joy_help&jd_joypark_task&jd_joy_park_help&jd_jxnc&adolf_jxhb&jd_necklace&jd_necklace_new&ZooFaker_Necklace&jd_angryKoi&jd_carnivalcity&jd_carnivalcity_help&gua_xmGame&jd_dyj_help&jd_fan&jd_golden_machine&jd_mohe&jd_beauty
    - timer: #超级直播间盲盒抽京豆#骁龙品牌日#财富岛收气球#口袋书店#半点京豆雨#京东天天加速#京东抽奖机#京东排行榜#财富大陆互助#东东健康社区#东东健康社区收集能量#超级直播间盲盒抽京豆#超级直播间红包雨#整点京豆雨
        parameters:
          name: 8jd_cfdqiqiu
          cronExpression: "1,30 0-23/1 * * *"
          enable: true
          argument: jd_super_mh&jd_guaxiaolong&jd_cfdqiqiu&jd_bookshop&jd_half_redrain&jd_speed&jd_lotteryMachine&jd_rankingList&jd_dogsEmploy&gua_wealth_island_help&jd_health&jd_health_collect&jd_super_mh&jd_live_redrain&jd_super_redrain
    - timer: #汽车生活节#京东零食街#特物Z简爱#特务Zx佳沛#超级粉丝互动#伊利养牛记(QQ星)#极速赚金币 种水果#柠檬许愿池#柠檬大富翁#柠檬七夕情报局#东东泡泡大战#旺财乐园#发财大赢家#来电好物季#荣耀焕新季#星系牧场#全民运动会守卫红包#京东全民开红包#柠檬是兄弟
        parameters:
          name: 9jd_lsj
          cronExpression: "0 14,44 9,8-23/1 * * * *"
          enable: true
          argument: jd_qcshj&jd_lsj&jd_twlove&jd_productZ4Brand&jd_wxFans&jd_ylyn&jd_wsdlb&jd_wish&jd_chinajoy&jd_qixi&gua_doge&jd_ppdz&jd_joy-park&jd_fcdyj&jd_fc&jd_kanjia&jd_foodRunning&jd_kanjia3&zy_ldhwj&jd_ryhxj&jd_qqxing&jd_olympicgames_guard&jd_redPacket&jd_kanjia2&zy_ryhxj&jd_fakersign
    - timer: #民奥运 激情奔跑#奥运夺金牌开卡#柠檬一次性开卡#汪汪乐园养joy#汪汪乐园脚本#京享值PK#价格保护#奶爸盛典 爸气全开#财富大陆#早起赢现金#京东多合一签到#早起福利
        parameters:
          name: 10gua-opencard
          cronExpression: "0 13,43 9,8-23/1 * * * *"
          enable: true
          argument: gua_olympic_opencard2&gua_opencard4&gua_opencard5&gua_opencard6&gua_opencard7&jd_opencard2&jd_joy_park_newtask&jd_jxzpk&jd_priceProtect&jx_cfdhb&jd_opencard_Daddy&gua_wealth_island&jd_morningSc&jd_bean_sign&gua_olympic_opencard&jd_zqfl&jd_joypark_joy&JD_DailyBonus&jd_angryCash
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
